name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of feature is this?
      options:
        - New Terraform Module
        - New Golden Path Template
        - New Agent
        - Workflow Improvement
        - Documentation
        - Developer Experience
        - Security Enhancement
        - Other
    validations:
      required: true

  - type: dropdown
    id: horizon
    attributes:
      label: Target Horizon
      description: Which horizon does this feature belong to?
      options:
        - H1 - Foundation
        - H2 - Enhancement
        - H3 - Innovation
        - Cross-cutting
        - Not applicable
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or use case...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or feature.
      placeholder: Describe the solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: List any alternative solutions...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would significantly improve experience
        - High - Blocking or critical need
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to contribute this feature
          required: false
        - label: I have searched for existing feature requests
          required: true
