# =============================================================================
# THREE HORIZONS ACCELERATOR - ARGOCD REPOSITORY CREDENTIALS
# =============================================================================
#
# Repository configurations for ArgoCD to access Git repos and Helm charts.
# Supports GitHub (HTTPS/SSH), Azure DevOps, and Helm repositories.
#
# =============================================================================

---
# =============================================================================
# GITHUB ORGANIZATION CREDENTIALS (HTTPS + PAT)
# =============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: repo-creds-github-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
stringData:
  # URL pattern for credential template
  url: https://github.com/{{ .Values.organization }}
  
  # GitHub PAT (recommend using ExternalSecret instead)
  password: ${GITHUB_PAT}
  username: x-access-token
  
  # Optional: GitHub App authentication (preferred for organizations)
  # githubAppID: "12345"
  # githubAppInstallationID: "67890"
  # githubAppPrivateKey: |
  #   -----BEGIN RSA PRIVATE KEY-----
  #   ...
  #   -----END RSA PRIVATE KEY-----

---
# =============================================================================
# GITHUB REPOSITORY CREDENTIALS (SSH)
# =============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: repo-creds-github-ssh
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
stringData:
  # SSH URL pattern
  url: git@github.com:{{ .Values.organization }}
  
  # SSH private key
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ${SSH_PRIVATE_KEY}
    -----END OPENSSH PRIVATE KEY-----

---
# =============================================================================
# AZURE DEVOPS REPOSITORY CREDENTIALS
# =============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: repo-creds-azure-devops
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
stringData:
  # Azure DevOps URL pattern
  url: https://dev.azure.com/{{ .Values.organization }}
  
  # PAT token
  password: ${AZURE_DEVOPS_PAT}
  username: x-token-auth

---
# =============================================================================
# HELM REPOSITORY - BITNAMI
# =============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: helm-repo-bitnami
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: bitnami
  url: https://charts.bitnami.com/bitnami
  type: helm
  enableOCI: "false"

---
# =============================================================================
# HELM REPOSITORY - PROMETHEUS COMMUNITY
# =============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: helm-repo-prometheus
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
  type: helm

---
# =============================================================================
# HELM REPOSITORY - GRAFANA
# =============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: helm-repo-grafana
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: grafana
  url: https://grafana.github.io/helm-charts
  type: helm

---
# =============================================================================
# HELM REPOSITORY - JETSTACK (CERT-MANAGER)
# =============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: helm-repo-jetstack
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: jetstack
  url: https://charts.jetstack.io
  type: helm

---
# =============================================================================
# HELM REPOSITORY - AZURE CONTAINER REGISTRY (OCI)
# =============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: helm-repo-acr
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: acr-helm
  url: oci://{{ .Values.acrName }}.azurecr.io/helm
  type: helm
  enableOCI: "true"
  username: ${ACR_USERNAME}
  password: ${ACR_PASSWORD}

---
# =============================================================================
# SPECIFIC REPOSITORY - PLATFORM GITOPS
# =============================================================================

apiVersion: v1
kind: Secret
metadata:
  name: repo-platform-gitops
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: platform-gitops
  url: https://github.com/{{ .Values.organization }}/platform-gitops.git
  type: git
  
  # Authentication (PAT)
  password: ${GITHUB_PAT}
  username: x-access-token
  
  # Optional: Insecure skip verify (not recommended for production)
  # insecure: "true"
  
  # Optional: Enable LFS
  # enableLfs: "true"

---
# =============================================================================
# EXTERNAL SECRET FOR GITHUB PAT (RECOMMENDED)
# =============================================================================

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: repo-creds-github-pat
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: repo-creds-github
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        url: "https://github.com/{{ .Values.organization }}"
        username: "x-access-token"
        password: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: github-pat-argocd

---
# =============================================================================
# EXTERNAL SECRET FOR GITHUB APP (ENTERPRISE)
# =============================================================================

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: repo-creds-github-app
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: repo-creds-github-app
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        url: "https://github.com/{{ .Values.organization }}"
        githubAppID: "{{ .appId }}"
        githubAppInstallationID: "{{ .installationId }}"
        githubAppPrivateKey: "{{ .privateKey }}"
  data:
    - secretKey: appId
      remoteRef:
        key: github-app-id
    - secretKey: installationId
      remoteRef:
        key: github-app-installation-id
    - secretKey: privateKey
      remoteRef:
        key: github-app-private-key

---
# =============================================================================
# REPOSITORY CERTIFICATE (FOR SELF-SIGNED CERTS)
# =============================================================================

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-tls-certs-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Add custom CA certificates here
  # git.example.com: |
  #   -----BEGIN CERTIFICATE-----
  #   ...
  #   -----END CERTIFICATE-----

---
# =============================================================================
# SSH KNOWN HOSTS
# =============================================================================

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-ssh-known-hosts-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-ssh-known-hosts-cm
    app.kubernetes.io/part-of: argocd
data:
  ssh_known_hosts: |
    # GitHub
    github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
    github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
    github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
    
    # Azure DevOps
    ssh.dev.azure.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H
    vs-ssh.visualstudio.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H
    
    # GitLab (if needed)
    # gitlab.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAfuCHKVTjquxvt6CM6tdG4SLp1Btn/nOeHHE5UOzRdf
    # gitlab.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Ber0gFNyW0QBkjAAwCkYPATAuCOYBS7dRPCgjoGSdmYC+oXoUIpkqb9/yjibLvDn/VYJ7E4owRUhoGYI7hZ5xYfbvYb5A6J/xOmAJdpB8p1n7F9RcAhNFG6DwsBEKgM0i6A0U5ORAloVf8M5r8SZe5r8pJT2JgcPX1BJq5p7/V7NMx6xqU2UQHKUKF1VlcgqANZHmMoP5dSrhQO7BrJQ

---
# =============================================================================
# GPG KEYS FOR COMMIT VERIFICATION (OPTIONAL)
# =============================================================================

apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-gpg-keys-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-gpg-keys-cm
    app.kubernetes.io/part-of: argocd
data:
  # Add GPG public keys for signed commit verification
  # Format: <key-id>: |
  #   -----BEGIN PGP PUBLIC KEY BLOCK-----
  #   ...
  #   -----END PGP PUBLIC KEY BLOCK-----

---
# =============================================================================
# CREDENTIAL TEMPLATES SUMMARY
# =============================================================================

apiVersion: v1
kind: ConfigMap
metadata:
  name: repo-creds-guide
  namespace: argocd
  annotations:
    description: "Guide for repository credential configuration"
data:
  README.md: |
    # Repository Credentials Guide
    
    ## Authentication Methods
    
    | Method | Use Case | Secret Type |
    |--------|----------|-------------|
    | HTTPS + PAT | Simple, short-lived tokens | repo-creds |
    | SSH Key | Long-lived, no rotation needed | repo-creds |
    | GitHub App | Enterprise, fine-grained permissions | repo-creds |
    | Azure DevOps PAT | ADO repositories | repo-creds |
    | OCI Registry | Helm charts in ACR/ECR | repository |
    
    ## Credential Templates vs Individual Repos
    
    - **Credential Template** (repo-creds): Matches URL prefix, applies to many repos
    - **Individual Repository** (repository): Specific repo with its own creds
    
    ## Best Practices
    
    1. Use ExternalSecrets for credential management
    2. Rotate PATs regularly (recommend GitHub App for long-term)
    3. Use SSH keys for automation, PATs for user access
    4. Enable commit signature verification for production
    5. Use OCI for Helm charts when possible (better security)
    
    ## Troubleshooting
    
    ```bash
    # List configured repositories
    argocd repo list
    
    # Test repository connection
    argocd repo get https://github.com/org/repo
    
    # Add repository manually
    argocd repo add https://github.com/org/repo \
      --username x-access-token \
      --password $GITHUB_PAT
    
    # Check SSH key fingerprint
    ssh-keygen -lf ~/.ssh/id_rsa
    ```
